# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e500306cb63343666931692ddccf792139b58d1073386ad4c7ad9eeb4c3777df69fec816ab09b41d06741e062bba1aa3dd2a3fc2ae0b852bf53189fc56b20ce

test:
  secret_key_base: f23c8e628f0f06b08b473dd4cf853f08c84b829d8cdb84ffb8fb27763104021e21d12134ba4bffb77dd786d0e5ad659c081c0122432ffa7e409a4431b287e8a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
